# gp sync example .gitpod.yml
# rename file before using

tasks:
  - name: Install npx and database
    before: |
      npm install -y npx
    init: |      
      npm install -y pg pgtools    
      npx --yes pg
      gp sync-done dbinstall
      
  - name: Install http-server
    init: |
      gp sync-await dbinstall
      npx --yes http-server
    command: curl http://localhost:8080