
tasks:
  - name: Install and Run Python 3.11
    init: |
      sudo add-apt-repository ppa:deadsnakes/ppa -y
      sudo apt update && sudo apt install -y python3.11

    command: |
      /usr/bin/python3.11 --version
     
