tasks:
  - name: Update OS Packages
    init: | 
      sudo apt update && sudo apt upgrade -y
      gp sync-done osupdate

  - name: Install Required Packages
    init: |
      gp sync-await osupdate
      sudo apt install -y install python3.11
    command: /usr/bin/python3.11 --version